.\"*******************************************************************
.\" Manual para PokemonGo-Sockets.
.\"*******************************************************************
.\" Comprimir este archivo con gzip:
.\" gzip PokemonGo-Sockets.1
.\" Como superusuario mover el comprimido en su ubicación adecuada.
.\" mv ./PokemonGo-Sockets.1.gz /usr/share/man/es/man1
.\" Ahora, ya podemos hacer referencia con:
.\" man PokemonGo-Sockets.1

.TH PokemonGo\-Sockets 8 "11 Dec 2018" "Versión 1.0" "Manual para PokemonGo\-Sockets"

.SH NOMBRE
pokemonGo.py

.SH SYNOPSIS
\fBpython3 pokemonGo.py\fP

.SH DESCRIPCIÓN
PokemonGo-Sockets es un programa que simula el famoso juego de PokémonGO en tiempo real.

.SH OPCIONES
\fBpokemonGo.py\fP no toma ninguna opción.

.SH EJEMPLOS
\fBpython3 pokemonGo.py\fP

.SH AUTORES
Martínez Flores Jorge Yael. (jmtz@ciencias.unam.mx)
Sánchez Morales Rodrigo Alejandro. (rodrigosanchez@ciencias.unam.mx)


.SH BUGS
No hay bugs conocidos.

.SH COPYRIGHT

.SH VÉASE TAMBIÉN
.\" Miscellaneous (including macro packages and conventions).
useradd(8), passwd(5), nuseradd.debian(8)